# load libraries
message ('Load R packages')
packages = c(
  'Seurat',
  'ggplot2',
  'gplots',
  'ggtree',
  'dplyr',
  'Matrix',
  'ggpubr',
  'biomaRt',
  'patchwork',
  'ComplexHeatmap',
  'RColorBrewer',
  'ggrepel',
  'fgsea',
  'tidyr',
  'gdata',
  'GSA',
#  'DropletUtils', 
  'harmony',
#  'scater',
  'destiny',
  'plotly',
  'GO.db', 
  'org.Mm.eg.db',
  'org.Hs.eg.db',
  'viridis',
  'BiocParallel',
  'ggridges',
  'clusterProfiler',
  'igraph',
  'tidyverse',
  'rstatix',
  'paletteer',
  'extrafont',
  'scCustomize',
  'circlize'
)
lapply(packages, require, character.only = TRUE)

